name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send heartbeat to Render app
        run: |
          URL="https://karsh.onrender.com/health"
          echo "Pinging $URL..."
          curl -fsS "$URL" || echo "⚠️ Failed to reach app"
